galaxy_info:
  author: Gabriel Iglesias
  description: Arquivo para configuração de gateway, firewall, failover e load-balancer entre 2 links de internet
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags: []
    - networking
    - gateway
    - firewall
    - load balancer
    - failover

dependencies []:

  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
