network:
    ethernets:
        enp3s0:
            addresses:
                - 10.10.10.2/24
            gateway4: 
            nameservers:
                addresses: [10.10.10.1, 1.1.1.1]
        enp6s0:
            addresses:
                - 192.168.0.4
            gateway:
            nameservers:
                addresses: [8.8.8.8, 8.8.4.4]
        enp8s0:
            addresses:
                - 192.168.0.4
            gateway: 
            nameservers:
                addresses: [8.8.8.8, 8.8.4.4]
                
    version: 2
