network:
    version: 2
    renderer: networkd
    ethernets:
        enp6s0:
            addresses:
                - 192.168.1.10/24
            nameservers:
                addresses: [8.8.8.8]
        
        enp4s0:
            addresses:    
                - 192.168.3.10/24
            nameservers:
                addresses: [8.8.8.8, 8.8.4.4]
        
        
        enp35s0f1:
            addresses:
                - 192.168.0.1/24
            nameservers:
                addresses: [8.8.8.8]
                
